# Generated by Django 3.2.25 on 2026-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_url',
            old_name='url',
            new_name='short_code',
        ),
        migrations.AlterField(
            model_name='short_url',
            name='created_at',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='short_url',
            name='updated_at',
            field=models.CharField(max_length=10),
        ),
    ]
